version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: sentry/sentry-laravel
    versions:
    - 2.3.1
    - 2.4.1
